# Site settings
author: Santiago Sendon
title: journey in code
header-img: img/home-bg.png
email: santiagosendon92@gmail.com
copyright_name: Santiago Sendon
description: > # this means to ignore newlines until "baseurl:"
  journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  santiagosendon

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
